# Generated by Django 5.1.6 on 2025-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_field', models.CharField(max_length=255, unique=True)),
                ('ecs_field', models.CharField(max_length=255)),
                ('embedding', models.BinaryField()),
                ('description', models.TextField(blank=True, null=True)),
                ('example_log_values', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ECSMappingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_field', models.CharField(max_length=255)),
                ('ecs_field', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=True)),
            ],
        ),
    ]
